export const USERS = [
  {
    id: 1,
    name: "John",
    isTalking: true,
    isMuted: false,
    image: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: 2,
    name: "Robert",
    isTalking: true,
    isMuted: false,
    image: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: 3,
    name: "Alex",
    isTalking: false,
    isMuted: true,
    image: "https://randomuser.me/api/portraits/men/47.jpg",
  },
  {
    id: 4,
    name: "Rebeca",
    isTalking: false,
    isMuted: false,
    image: "https://randomuser.me/api/portraits/women/59.jpg",
  },
  {
    id: 5,
    name: "Helia",
    isTalking: false,
    isMuted: true,
    image: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    id: 6,
    name: "Jacob",
    isTalking: false,
    isMuted: false,
    image: "https://randomuser.me/api/portraits/men/76.jpg",
  },
  {
    id: 7,
    name: "Anahita",
    isTalking: false,
    isMuted: true,
    image: "https://randomuser.me/api/portraits/women/81.jpg",
  },
]
